# Generated by Django 3.0.6 on 2020-05-25 22:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0002_auto_20200525_2248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleEvent',
            new_name='Author',
        ),
    ]
